// Mocks generated by Mockito 5.4.6 from annotations
// in qlm_guardian_app_v5/test/features/registry/presentation/providers/add_registry_entry_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:qlm_guardian_app_v5/core/network/api_client.dart' as _i9;
import 'package:qlm_guardian_app_v5/core/network/interceptors/auth_interceptor.dart'
    as _i3;
import 'package:qlm_guardian_app_v5/features/registry/data/models/contract_type_model.dart'
    as _i7;
import 'package:qlm_guardian_app_v5/features/registry/data/models/form_field_model.dart'
    as _i8;
import 'package:qlm_guardian_app_v5/features/registry/data/repositories/registry_repository.dart'
    as _i5;
import 'package:qlm_guardian_app_v5/features/system/data/models/registry_entry_sections.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRegistryEntrySections_0 extends _i1.SmartFake
    implements _i2.RegistryEntrySections {
  _FakeRegistryEntrySections_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthInterceptor_1 extends _i1.SmartFake
    implements _i3.AuthInterceptor {
  _FakeAuthInterceptor_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_2 extends _i1.SmartFake implements _i4.Dio {
  _FakeDio_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_3<T1> extends _i1.SmartFake implements _i4.Response<T1> {
  _FakeResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RegistryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegistryRepository extends _i1.Mock
    implements _i5.RegistryRepository {
  MockRegistryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.RegistryEntrySections>> getEntries() =>
      (super.noSuchMethod(
            Invocation.method(#getEntries, []),
            returnValue: _i6.Future<List<_i2.RegistryEntrySections>>.value(
              <_i2.RegistryEntrySections>[],
            ),
          )
          as _i6.Future<List<_i2.RegistryEntrySections>>);

  @override
  _i6.Future<List<_i7.ContractTypeModel>> getContractTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getContractTypes, []),
            returnValue: _i6.Future<List<_i7.ContractTypeModel>>.value(
              <_i7.ContractTypeModel>[],
            ),
          )
          as _i6.Future<List<_i7.ContractTypeModel>>);

  @override
  _i6.Future<List<_i8.FormFieldModel>> getFormFields(int? typeId) =>
      (super.noSuchMethod(
            Invocation.method(#getFormFields, [typeId]),
            returnValue: _i6.Future<List<_i8.FormFieldModel>>.value(
              <_i8.FormFieldModel>[],
            ),
          )
          as _i6.Future<List<_i8.FormFieldModel>>);

  @override
  _i6.Future<_i2.RegistryEntrySections> createEntry(
    _i2.RegistryEntrySections? entry, {
    String? attachmentPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createEntry,
              [entry],
              {#attachmentPath: attachmentPath},
            ),
            returnValue: _i6.Future<_i2.RegistryEntrySections>.value(
              _FakeRegistryEntrySections_0(
                this,
                Invocation.method(
                  #createEntry,
                  [entry],
                  {#attachmentPath: attachmentPath},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.RegistryEntrySections>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i9.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthInterceptor get authInterceptor =>
      (super.noSuchMethod(
            Invocation.getter(#authInterceptor),
            returnValue: _FakeAuthInterceptor_1(
              this,
              Invocation.getter(#authInterceptor),
            ),
          )
          as _i3.AuthInterceptor);

  @override
  _i4.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_2(this, Invocation.getter(#dio)),
          )
          as _i4.Dio);

  @override
  _i6.Future<_i4.Response<T>> get<T>(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {#queryParameters: queryParameters, #options: options},
            ),
            returnValue: _i6.Future<_i4.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {#queryParameters: queryParameters, #options: options},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response<T>>);

  @override
  _i6.Future<_i4.Response<T>> post<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
              },
            ),
            returnValue: _i6.Future<_i4.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response<T>>);

  @override
  _i6.Future<_i4.Response<T>> put<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
              },
            ),
            returnValue: _i6.Future<_i4.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response<T>>);

  @override
  _i6.Future<_i4.Response<T>> delete<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
              },
            ),
            returnValue: _i6.Future<_i4.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response<T>>);
}
