// Mocks generated by Mockito 5.4.6 from annotations
// in qlm_guardian_app_v5/test/features/registry/presentation/providers/add_registry_entry_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:qlm_guardian_app_v5/core/network/api_client.dart' as _i8;
import 'package:qlm_guardian_app_v5/core/network/interceptors/auth_interceptor.dart'
    as _i2;
import 'package:qlm_guardian_app_v5/features/registry/data/models/contract_type_model.dart'
    as _i6;
import 'package:qlm_guardian_app_v5/features/registry/data/models/form_field_model.dart'
    as _i7;
import 'package:qlm_guardian_app_v5/features/registry/data/repositories/registry_repository.dart'
    as _i4;
import 'package:qlm_guardian_app_v5/features/system/data/models/registry_entry_sections.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthInterceptor_0 extends _i1.SmartFake
    implements _i2.AuthInterceptor {
  _FakeAuthInterceptor_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_1 extends _i1.SmartFake implements _i3.Dio {
  _FakeDio_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_2<T1> extends _i1.SmartFake implements _i3.Response<T1> {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegistryEntrySections_3 extends _i1.SmartFake
    implements _i9.RegistryEntrySections {
  _FakeRegistryEntrySections_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RegistryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegistryRepository extends _i1.Mock
    implements _i4.RegistryRepository {
  MockRegistryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i9.RegistryEntrySections>> getEntries() =>
      (super.noSuchMethod(
            Invocation.method(#getEntries, []),
            returnValue: _i5.Future<List<_i9.RegistryEntrySections>>.value(
              <_i9.RegistryEntrySections>[],
            ),
          )
          as _i5.Future<List<_i9.RegistryEntrySections>>);

  @override
  _i5.Future<List<_i6.ContractTypeModel>> getContractTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getContractTypes, []),
            returnValue: _i5.Future<List<_i6.ContractTypeModel>>.value(
              <_i6.ContractTypeModel>[],
            ),
          )
          as _i5.Future<List<_i6.ContractTypeModel>>);

  @override
  _i5.Future<List<_i7.FormFieldModel>> getFormFields(int? typeId) =>
      (super.noSuchMethod(
            Invocation.method(#getFormFields, [typeId]),
            returnValue: _i5.Future<List<_i7.FormFieldModel>>.value(
              <_i7.FormFieldModel>[],
            ),
          )
          as _i5.Future<List<_i7.FormFieldModel>>);

  @override
  _i5.Future<_i9.RegistryEntrySections> createEntry(
    _i9.RegistryEntrySections? entry, {
    String? attachmentPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createEntry,
              [entry],
              {#attachmentPath: attachmentPath},
            ),
            returnValue: _i5.Future<_i9.RegistryEntrySections>.value(
              _FakeRegistryEntrySections_3(
                this,
                Invocation.method(
                  #createEntry,
                  [entry],
                  {#attachmentPath: attachmentPath},
                ),
              ),
            ),
          )
          as _i5.Future<_i9.RegistryEntrySections>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i8.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthInterceptor get authInterceptor =>
      (super.noSuchMethod(
            Invocation.getter(#authInterceptor),
            returnValue: _FakeAuthInterceptor_0(
              this,
              Invocation.getter(#authInterceptor),
            ),
          )
          as _i2.AuthInterceptor);

  @override
  _i3.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_1(this, Invocation.getter(#dio)),
          )
          as _i3.Dio);

  @override
  _i5.Future<_i3.Response<T>> get<T>(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {#queryParameters: queryParameters, #options: options},
            ),
            returnValue: _i5.Future<_i3.Response<T>>.value(
              _FakeResponse_2<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {#queryParameters: queryParameters, #options: options},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.Response<T>>);

  @override
  _i5.Future<_i3.Response<T>> post<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
              },
            ),
            returnValue: _i5.Future<_i3.Response<T>>.value(
              _FakeResponse_2<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i3.Response<T>>);

  @override
  _i5.Future<_i3.Response<T>> put<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
              },
            ),
            returnValue: _i5.Future<_i3.Response<T>>.value(
              _FakeResponse_2<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i3.Response<T>>);

  @override
  _i5.Future<_i3.Response<T>> delete<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
              },
            ),
            returnValue: _i5.Future<_i3.Response<T>>.value(
              _FakeResponse_2<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i3.Response<T>>);
}
